services:
  - type: web
    name: brevardmapper-api
    env: native
    plan: free
    rootDir: BrevardMapper.API
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/BrevardMapper.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production